title: Meu Blog
description: >-
  Um espaço para compartilhar ideias, anotações e projetos.
author: Kayo Antoniazzi

markdown: kramdown
plugins:
  - jekyll-feed

# Menu de navegação (aparece no topo do site, nesta ordem)
header_pages:
  - about.md
  - playlist.md

# Não precisa mexer aqui embaixo
permalink: /:year/:month/:day/:title/
